<a href="https://colab.research.google.com/github/Debayan97531/Maths_in_ML/blob/main/Matrix2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Matrix Addition

Two Matrices can be added only if they have same shape

In [2]:
#creating two matrices

A=np.array([[2,3],[5,6]])

B=np.array([[6,7],[8,9]])

print(A)

print(B)

[[2 3]
 [5 6]]
[[6 7]
 [8 9]]


In [3]:
sum=A+B
print(sum)

[[ 8 10]
 [13 15]]


In [6]:
#create two matrices with random values

matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))


print(matrix_1)
print(matrix_2)

[[4 6 6]
 [4 9 9]
 [2 8 6]]
[[12 14 11]
 [ 5  2 10]
 [13  4 14]]


In [7]:
sum = np.add(matrix_1,matrix_2)

print(sum)

[[16 20 17]
 [ 9 11 19]
 [15 12 20]]


In [8]:
#create two matrices with random values with diff shape

mat_3 = np.random.randint(10, size=(3,3))
mat_4 = np.random.randint(15, size=(3,4))

sum_2=np.add(mat_3,mat_4)

ValueError: ignored

wr get this error bcs shape of mat_3 and mat_4 are different

In [9]:
#creating two matrices

A= np.array([[2,3],[4,5]])

B= np.array([[6,7],[8,9]])

print(A)
print(B)

[[2 3]
 [4 5]]
[[6 7]
 [8 9]]


In [10]:
diff=A-B
print(diff)

[[-4 -4]
 [-4 -4]]


In [11]:
#creating two matrices with random values

mat_1 = np.random.randint(15, size=(3,4))
mat_2 = np.random.randint(5, size=(3,4))

print(mat_1)
print(mat_2)

[[12 11 14  5]
 [11  2  4  6]
 [12 11  8  4]]
[[4 4 0 4]
 [1 0 0 4]
 [2 4 2 4]]


In [12]:
diff = np.subtract(mat_1,mat_2)
print(diff)

[[ 8  7 14  1]
 [10  2  4  2]
 [10  7  6  0]]


Maultiplying a matrix by a scalar

In [13]:
x=5
y= np.random.randint(5, size=(3,3))
print(y)

[[2 0 1]
 [2 0 0]
 [0 2 4]]


In [14]:
product = np.multiply(x,y)
print(product)

[[10  0  5]
 [10  0  0]
 [ 0 10 20]]


Multiplying 2 matrices

In [15]:
#create two matrices with random values

mat_3 = np.random.randint(5, size=(3,3))
mat_4 = np.random.randint(5, size=(3,4))

print(mat_3)
print(mat_4)

[[1 2 1]
 [3 4 3]
 [1 0 1]]
[[2 3 4 4]
 [0 3 1 1]
 [0 3 1 0]]


In [16]:
product = np.dot(mat_3,mat_4)
print(product)

[[ 2 12  7  6]
 [ 6 30 19 16]
 [ 2  6  5  4]]


In [17]:
product.shape

(3, 4)

In [18]:
#create two matrices with random values
mat_3 = np.random.randint(4, size=(3,3))
mat_4 = np.random.randint(5, size=(3,3))

print(mat_3)
print(mat_4)

[[3 3 1]
 [1 2 1]
 [3 0 3]]
[[1 4 3]
 [2 3 1]
 [0 1 4]]


In [19]:
product = np.multiply(mat_3,mat_4)
print(product)

[[ 3 12  3]
 [ 2  6  1]
 [ 0  0 12]]


In [20]:
#create two matrices with random values

mat_3 = np.random.randint(4, size=(3,3))
mat_4 = np.random.randint(4, size=(3,4))

product = np.multiply(mat_3,mat_4)
print(product)

ValueError: ignored

np.multiply() allows multiply with same size matrices only