<a href="https://colab.research.google.com/github/Debayan97531/Maths_in_ML/blob/main/matrix_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Creating a matrix using numpy

In [5]:
matrix_1 = np.array([[2,4],[6,7],[88,9]])
print(matrix_1)

[[ 2  4]
 [ 6  7]
 [88  9]]


In [6]:
matrix_1.shape

(3, 2)

Creating matrices with random values

In [7]:
ran_mat = np.random.rand(3,4)
print(ran_mat)

[[0.71319701 0.02814538 0.2607529  0.10967044]
 [0.08261445 0.98414741 0.25916851 0.64011979]
 [0.76397473 0.82568715 0.85576669 0.17079717]]


In [8]:
#creating with random integers

ran_int_mat = np.random.randint(100,size=(3,5))
print(ran_int_mat)

[[19 40 96 89 40]
 [13 23 31 70 25]
 [87 69 96 89 42]]


with all values as 1

In [10]:
mat_3 = np.ones((2,3))
print(mat_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
matrix_3 = np.ones((2,3),dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null / Zero Matrix

In [14]:
mat_4 = np.zeros((4,5))
print(mat_4)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [15]:
matrix_4 = np.zeros((4,6),dtype=int)
print(matrix_4)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


Identity Matrix

In [18]:
iden_mat = np.eye(3,4)
print(iden_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


Transpose of a matrix

In [19]:
#with random values

a = np.random.randint(100,size=(4,5))
print(a)

[[98 22 10 49  6]
 [75 43 91 16 64]
 [75 79 46 23  9]
 [60 35 25  0 86]]


In [20]:
tran_a = np.transpose(a)
print(tran_a)

[[98 75 75 60]
 [22 43 79 35]
 [10 91 46 25]
 [49 16 23  0]
 [ 6 64  9 86]]
