<a href="https://colab.research.google.com/github/Debayan97531/Maths_in_ML/blob/main/matrix_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Matrix **Addittion**
two matrices an be added only of same shape

In [2]:
a= np.array([[2,3],[5,8]])
b= np.array([[3,6],[7,9]])

print(a)
print(b)

[[2 3]
 [5 8]]
[[3 6]
 [7 9]]


In [3]:
sum=a+b
print(sum)

[[ 5  9]
 [12 17]]


In [4]:
sum=np.add(a,b)
print(sum)

[[ 5  9]
 [12 17]]


In [7]:
#create two matrices of random values
mat_1= np.random.randint(100,size=(3,5))
mat_2= np.random.randint(20,size=(3,5))
mat_3= np.random.randint(10,size=(3,4))

sum_1=np.add(mat_1,mat_2)
print(sum_1)

sum_2=np.add(mat_2,mat_3)
print(sum_2)

[[87 35 61 32 85]
 [14 98 29 32 74]
 [61 81 67  6 76]]


ValueError: ignored

In [8]:
diff_1=np.subtract(mat_1,mat_2)
print(diff_1)

diff_2=np.subtract(mat_2,mat_3)
print(diff_2)

[[57 -1 37 28 53]
 [14 62 17 32 60]
 [29 71 39  0 60]]


ValueError: ignored

multiply with a scalar

In [9]:
x=5
y= np.random.randint(10,size=(3,4))

product= np.multiply(x,y)
print(product)

[[10 45 20 15]
 [ 5 45 20 20]
 [25 30 10 25]]


multiply two matrices

In [17]:
mat_3= np.random.randint(10,size=(3,3))
mat_4= np.random.randint(20,size=(3,4))
mat_5= np.random.randint(20,size=(4,4))

print(mat_3)
print(mat_4)
print(mat_5)

pro=np.dot(mat_3,mat_4)
print(pro)
pro.shape

pro_2=np.dot(mat_4,mat_5)
print(pro_2)
pro_2.shape

pro_3=np.dot(mat_3,mat_5)
print(pro_3)

[[2 6 6]
 [0 6 0]
 [2 5 1]]
[[12  0  8 13]
 [ 4  2 13 15]
 [ 7 19 14  4]]
[[17 16 11  4]
 [ 1 18  8 16]
 [17 11 10 19]
 [18  2  5  9]]
[[ 90 126 178 140]
 [ 24  12  78  90]
 [ 51  29  95 105]]
[[574 306 277 317]
 [561 273 265 430]
 [448 616 389 634]]


ValueError: ignored

element wise matrix multiplicaation

valid only when matrices of same shape

In [18]:
mat_3= np.random.randint(10,size=(3,3))
mat_4= np.random.randint(20,size=(3,3))

pro_4 = np.multiply(mat_3,mat_4)
print(pro_4)

[[81 42  6]
 [16 40 48]
 [ 0 70  0]]


In [19]:
mat_3= np.random.randint(10,size=(3,3))
mat_4= np.random.randint(20,size=(3,4))

pro_5=np.multiply(mat_3,mat_4)
print(pro_5)

ValueError: ignored