<a href="https://colab.research.google.com/github/Debayan97531/Maths_in_ML/blob/main/Matrix1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [4]:
matrix_1 = np.array([[2,3],[6,7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [5]:
matrix_1.shape

(2, 2)

In [6]:
matrix_2 = np.array([[10,35,46],[50,68,33],[20,15,90]])
print(matrix_2)

[[10 35 46]
 [50 68 33]
 [20 15 90]]


In [7]:
matrix_2.shape

(3, 3)

Creating matrix with random variables

In [8]:
random_matrix = np.random.rand(3,3)
print(random_matrix)

[[0.2070532  0.63354506 0.77153839]
 [0.80861331 0.99090277 0.00119874]
 [0.35521011 0.76048114 0.61046195]]


In [9]:
#creating matrix withrandom integers
random_integer_matrix  = np.random.randint(100,size=(4,5))
print(random_integer_matrix)

[[ 7 58 15 93  2]
 [12 90 91 44 97]
 [18 11 92  2 69]
 [89 74 50  8 64]]


Matrix with all values as 1

In [11]:
matrix_3 = np.ones((2,3))
print(matrix_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [12]:
matrix_3 = np.ones((6,6) , dtype=int)
print(matrix_3)

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]


Null matrix or Zero Matrix

In [13]:
null_matrix = np.zeros((7,7))
print(null_matrix)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
null_matrix = np.zeros((3,2), dtype=int)
print(null_matrix)

[[0 0]
 [0 0]
 [0 0]]


Identity matrix

In [17]:
iden_mat= np.eye(3,3)
print(iden_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [22]:
iden_mat = np.eye(4,4)
print(iden_mat)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Transpose of matrix

In [23]:
a = np.random.randint(100, size=(4,5))
print(a)

[[28 78 69 20 27]
 [64 21 68 71 64]
 [30 97 23 98 40]
 [49 69 59  4 49]]


In [24]:
trans_of_a = np.transpose(a)
print(trans_of_a)

[[28 64 30 49]
 [78 21 97 69]
 [69 68 23 59]
 [20 71 98  4]
 [27 64 40 49]]


In [27]:
b = np.random.randint(10, size=(3,4))
print(b)

[[7 9 5 8]
 [0 8 1 6]
 [0 9 6 2]]


In [28]:
trans_of_b = np.transpose(b)
print(trans_of_b)

[[7 0 0]
 [9 8 9]
 [5 1 6]
 [8 6 2]]
